# Generated by Django 4.2.13 on 2024-07-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_item_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Barangay',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Citizenship',
        ),
        migrations.RemoveField(
            model_name='item',
            name='City',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Civil_Status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='College',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Date_of_Birth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Elementary',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Fathers_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Mothers_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Place_of_Birth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Religion',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Secondary',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Sex',
        ),
        migrations.RemoveField(
            model_name='item',
            name='State',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Student_No',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ZipCode',
        ),
        migrations.RemoveField(
            model_name='item',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='middlename',
        ),
        migrations.AddField(
            model_name='item',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='blood_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='graduate_studies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vocational',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='civil_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='elementary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='secondary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
